# Generated by Django 4.2 on 2023-05-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('user_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address_line_1', models.CharField(max_length=30)),
                ('address_line_2', models.CharField(blank=True, max_length=30, null=True)),
                ('postcode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('user_id', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('currency_id', models.PositiveSmallIntegerField()),
                ('fee', models.FloatField()),
                ('confirmed', models.BooleanField(default=False)),
                ('recipient_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('salt', models.CharField(max_length=30)),
                ('balance', models.FloatField()),
                ('currency_id', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
