# Generated by Django 4.2 on 2023-05-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
