# Generated by Django 4.2 on 2023-05-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency_id',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='currency_id',
            field=models.CharField(max_length=3),
        ),
    ]
